#!/usr/bin/bash

script_root=$(dirname "$0")

custom_file="${script_root}/custom.txt"
template_file="${script_root}/forward_white.action.template"

list_root="$script_root"

domin_list=(
    'apple.china.conf'
    'google.china.conf'
    'accelerated-domains.china.conf')
domin_list=("${domin_list[@]/#/${list_root}/}")


{
    cat "$template_file";
    {
        cat ${domin_list[@]} | sed 's|server=/\([^/]*\)/.*$|.\1|';
        [ -f "$custom_file" ] && cat "$custom_file";
    } | sort | uniq ;
} > forward_white.action
